module.exports = {
	/* ###Mark: General Usage### */
	"Type `cancel` to cancel this command.": "Napisz `cancel` (anuluj), żeby anulować tą komendę.",
	"There are not enough arguments to this command. The minimum is {0}.": "Nie ma odpowiednio dużo argumentów do tej komendy. Minimum to {0}.",
	"by {0}": "przez {0}",
	"Time ran out, command has been cancelled.": "Czas się skończył, komenda została odwołana.",
	"Too many retries, command has been cancelled.": "Zbyt dużo prób, komenda została odwołana.",
	"Command has been cancelled.": "Komenda została odwołana.",
	
	/* ###Mark: Commands Commands### */
	"No description available.": "Brak opisu",
	"Total Commands: {0}": "Liczba komend: {0}",

	/* ###Mark: ImgInfo command### */
	"Format": "Format",
	"Dimentions": "Wymiary",
	"Width": "Szerokość",
	"Height": "Wysokość",
	"{0} pixels": "{0} <'{0}' == '1' ? 'piksel' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'pikseli' : 'piksele')>",

	/* ###Mark: Language command### */
	"The language has been changed to {0} **{1}**.": "Język został zmieniony to {0} **{1}**.",
	// "Which language would you like to set? \nHere is a list of the available languages:": "Che lingua vorresti impostare? \nEcco una lista di lingue disponibili:",
	// "That is an invalid language. Here are the available languages:": "Quella non è una lingua valida. Ecco le lingue disponibili:",

	"I couldn't find the requested information.": "Nie mogłem znaleźć żądanej informacji.",
	"Author": "Autor",	
	"commander of this package decided to unpublish it.": "autor tego pakietu zdecydował go usunąć.",
	"Image information requested by {0}": "Informacje o obrazie żądane przez {0}",
	"Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "Wybierz numer pomiędzy 1 a {0} (za jedną minutę komenda zostanie odwołana)",
	"Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown":  "W ciągu następnych 30 sekund, musisz wybrać numer między 1 a {0}. Komenda zostanie automatycznie zatrzymana w ciągu 30 sekund, jeśli wybór nie został wykonany. Alternatywnie wpisz `cancel`, żeby ręcznie zatrzymać komendę, omijając czasomierz.",
	"Progress": "Postęp",
	"Requested by {0}": "Żądane przez {0}",
	"I think it may work better if you are in a voice channel!": "Myślę, że to zadziała lepiej, jeśli będziesz w kanale głosowym...",
	"Now Playing: {0}": "Teraz gramy: {0}",
	"there isn't any music playing. :P": "żadna muzyka nie gra. :P",
	"I have successfully paused {0}.": "Szczęśliwie zatrzymałem {0}.",
	"Examples": "Przykłady",
	"Aliases": "Pseudonimy",
	"Permissions": "Uprawnienia",
	"Category": "Kategoria",
	"Help for command \"{0}\"": "Pomoc dla komendy \"{0}\"",
	'To view a list of all the commands, go to the [Yamamura Website Command Page]({0}).': "Żeby zobaczyć listę wszystkich komend, przyjdź na [stronę komend strony bota Yamamura]({0}).",
	"To view a list of a command of a specific category, type `{0}commands (category name)`.": "Żeby zobaczyć listę komend specyficznej kategorii, wpisz `{0}commands (nazwa kategorii)`",
	"Command Listing": "Lista Komend",
	"{0}ms": "{0}ms",
	"The message round-trip took {0}": "Wysłanie wiadomości w obie strony trwało {0}",
	"The heartbeat ping is {0}": 'Ping "bicie serca :heart:" trwał {0}',
	"Welcome to {0}": "Witamy do {0}",
	"This is a discord bot made in Discord-Akairo written for MakerBoard connectivity.": "To jest bot Discord-owy stworzony w Discord-Akairo stworzonym przez społeczność MakerBoard",
	"If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Jeśli chcesz zobaczyć wszystkie dostępne komendy, proszę sprawdzić naszą stronę, lub wpisać {0}commands",
	"Publicity": "Publiczność",
	"Usage": "Użycie",
	"Resource Usage": "Użycie zasobów",
	"Backends": "Backendy",
	"Database System": "System bazy danych",
	"day": "dzień",
	"days": "dni",
	"hours": "<'{0}' == '1' ? 'godzina' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'godziny' : 'godzin')>",
	"hours": "<'{0}' == '1' ? 'godzina' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'godziny' : 'godzin')>",
	"minute": "<'{0}' == '1' ? 'minuta' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'minuty' : 'minut')>",
	"minutes": "<'{0}' == '1' ? 'minuta' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'minuty' : 'minut')>",
	"second": "<'{0}' == '1' ? 'sekunda' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'sekundy' : 'sekund')>",
	"seconds": "<'{0}' == '1' ? 'sekunda' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'sekundy' : 'sekund')>",
	"and": "i",
	"ago": "temu",
	"Uptime": "Czas pracy",
	"Creation date": "Data utworzenia",
	"Total Events": "Liczba wydarzeń",
	"{0} total commands": "{0} komend",
	"{0} total listeners": "{0} słuchaczy ogółem",
	"You didn't specify a key!": "Nie określiłeś/aś frazy kluczowej!",
	"You didn't specify a value!": "Nie określiłeś/aś wartości!",
	"Are you ___**100%**___ sure you want to reset the configuration? [Y/N]": "Jesteś/aś ___**100%**___ pewny/pewna chcesz zresetować konfigurację? [Y (tak)/N (nie)]",
	"action cancelled": "akcja anulowana",
	"There's no `{0}` key in the configuration!": "Nie ma klucza `{0}` w konfiguracji!",
	"I have successfully cleared the configuration": "Pomyślnie wyczyszczono konfigurację.",
	"There has been an error with the configuration clearance. Please report this bug to the {0} Developers": "Si è verificato un errore durante il ripristino della configurazione. Proszę zgłosić ten błąd do {0} Deweloperów",
	"{0} - by {1}": "{0} - przez {1}",
	"An error occurred: {0}.\nAlert the bot owners to let them fix this error": "Wystąpił błąd: {0}.\nOstrzeż właścicieli bota, żeby mogli naprawić ten błąd", 
	"There's no type with ID `{0}`": "Nie istnieje typ z ID `{0}`",
	"The action must be one of [{0}]!": "Akcja musi być jedną z [{0}]!",
	"Server configuration for {0}": "Konfiguracja serwera dla {0}",
	"This value is empty": "Ta wartość jest pusta",
	"You can use `{0}config set <key> null` to set a value to an empty state.": "Możesz użyć `{0}config set <klucz> null`, żeby ustawić wartość na pustą.",
	"The input `{0}` is not valid for the type `{1}`.": "Dane wejściowe `{0}` są nieprawidłowe dla typu `{1}`",
	"Administration": "Administracja",
	"Experience Points": "Punkty Doświadczenia",
	"Games": "Gry",
	"MakerBoard Connectivity": "Łączność MakerBoard",
	"Useful": "Użyteczne",
	"Audio": "Audio",
	"Fun": "Zabawne",
	"Image Edits": "Edycje Obrazów",
	"Moderation": "Moderacja",
	"Bot Utilities": "Narzędzia bota",
	"Game Server Statistics": "Statystyki serwera z grami",
	"Image Fun": "Zabawa z obrazami",
	"Text Edits": "Edycje Tekstu",
	"View and set your server's config for the bot.": "Wyświetl i modyfikuj twoją konfigurację twojego serwera dla bota.",
	"Log channel": "Kanał na logi",
	"Welcome channel": "Kanał przywitań",
	"Welcome messages": "Messaggi di benvenuto",
	"Leave message": "Wiadomość pożegnania",
	"Prefix": "Prefiks",
	"MakerBoard URL": "URL MakerBoarda",
	"Starboard channel": "Kanał Starboard",
	"Level UP messages": "Wiadomości o awansowaniu",
	"Level UP": "Awans",
	"Muted role": "Wyciszona rola",
	"You need to have the configuration key `mutedrole` set in order for this command to work.": "Potrzebujesz ustawioną frazę konfiguracyjną `mutedrole`, żeby komenda zadziałała.",
	"The user you wanted to mute needs to be in this server in order for this command to work.": "Użytkownik, którego próbowałeś wyciszyć musi być w tym serwerze, żeby komenda zadziałała.",
	"Administrators can't be muted. It wouldn't affect them.": "Administratorzy nie mogą być wyciszeni. To nie miałoby efektu.", // Hard translation - indepth6
	"You need to have the `Administrator` permission in order to mute moderators.": "Musisz mieć pozwolenie `Administrator`, żeby wyciszać moderatów.",
	"You can't mute someone who has a higher role position than you.": "Nie możesz wyciszyć kogoś, kto ma wyższą rolę niż ty.",
	"You can't mute yourself!": "Nie możesz wyciszyć samego siebie! :duck:!",
	"{0} was successfully muted": "{0} został pomyślnie wyciszony",
	"{0} was successfully unmuted": "{0} został pomyślnie nie wyciszony",
	"an error occured while trying to mute the user. Report this error to the Yamamura developers: `{0}`": "wystąpił błąd próbując wyciszyć użytkownika. Zgłoś ten błąd to deweloperów Yamamura: `{0}`",
	"Enabled": "Włączone",
	"Disabled": "Wyłączone",
	"Requested by {0}": "Żądane przez {0}",
	"I have successfully paused {0}.": "Pomyślnie zatrzymałem {0}.",
	"I think it may work better if you are in a voice channel!": "Myślę, że to zadziała lepiej, jeśli będziesz w kanale głosowym...",
	"Now Playing: {0}": "Teraz gram: {0}",

	"there currently isn't any music playing in this server.": "na razie nie ma żadnej muzyki w tym serwerze.",
	"I have successfully cleared the configuration": "Pomyślnie wyczyściłem konfigurację 💻 ",
	"I couldn't get text to mock.": "Nie mogłem znaleźć tekstu do naśmiewania'",
	"There were no text I can find to convert to hexadecimal.": "Nie było tekstu, który mogłem skonwertować na heksadecymalny.",
	'There was no Bs found in the text': "Nie znaleziono B w tekście",
	"Related Videos": 'Propozycje',
	"in order to pause audio, there needs to be audio playing in the channel": 'żeby zatrzymać audio, musi grać audio w kanale.',
	"in order to resume audio, there needs to be audio playing in the channel": 'żeby wznowić audio, musi grać audio w kanale',
	'Pause the currently playing audio.': 'Zatrzymuje aktualnie grające audio.',
	'Shows information on the currently playing song.': 'Pokazuje informacje o aktualnie grającej piosence.',
    'Plays the audio of a Youtube video.': 'Gra audio z wideo YouTube.',
    'Please state a song from Youtube you\'d like to listen to': 'Proszę określić piosenkę, którą chcesz wysłuchać',
    'That\'s not a valid song! Try again.': 'To nie jest prawidłowa piosenka! Spróbuj ponownie.',
    'Shows the music queue for the current server.': 'Pokazuje kolejkę na tym serwerze.',
    "you need to be in a voice channel in order for me to play music": "musisz być w kanale głosowym, żebym grał muzykę",
    "You lost perms to connect to the Voice Channel.": "Straciłeś uprawnienia, żeby dołączyć do kanału głosowego. 😂",
	"I can't join. Make sure I have the proper permissions.": "Nie mogę dołączyć. Upewnij się, czy mam odpowiednie uprawnienia. 🤔",
    "I can't speak. Make sure I have the proper permissions.": "Nir mogę mówić. Upewnij się, czy mam odpowiednie uprawnienia. 🤔",
    "Related Music Search": "Związane wyniki",
	"Added {0} song(s) to Queue: {1} | Requested by: {2}": "Liczba piosenek dodanych do kolejki: {0} ({1}) | Żądane przez {2}",
    "Added to Queue: {0} | Requested by: {1}": "Dodano do kolejki ({0})",
    "**NOW PLAYING**: [{0}]({1}) | Requested by {2}": "**TERAZ GRAMY**: [{0}] ({1}) | Żądane przez: {2}",
    "**NEXT**: [{0}]({1}) | Requested by {2}": "**NASTĘPNA PIOSENKA**: [{0}] ({1}) | Żądane przez {2}",
	"{0} Users": "Liczba użytkowników: {0}",
	"{0} Channels": "Liczba kanałów: {0}",
	"{0} Servers": "Liczba serwerów: {0}",
	"You are missing {0} to use that command.": "Wymagasz uprawnienia {0} żeby użyć tej komendy.",
	"I'm missing {0} to use that command.": "Potrzebuję {0}, żeby użyć tej komendy.",
	"{0} is an all-in-one Discord bot dedicated to helping modding communities and more.": "{0} jest wielofunkcyjnym botem Discord dedykowanym, żeby pomóc społecznościom na temat modowania itd.",
	"Type \`cancel\` to cancel this command.": "Napisz \`cancel`\ (anuluj), żeby anulować tą komendę",
	"It can fulfill your server's moderation needs and create fun events for your community to enjoy": "Może wypełnić portzeby moderacji twojego serwera i stworzyć fajne wydarzenia dla twojej społeczności"
}