module.exports = {
    "No description available.": "Brak opisu",
"Total Commands: {0}": "Liczba komend: {0}",
"There are not enough arguments to this command. The minimum is {0}.": "Nie ma odpowiednio dużo argumentów do tej komendy. Minimum to {0}.",
"The language has been changed to {0} **{1}**.": "Język został zmieniony to {0} **{1}**.",
"Format": "Format",
"Dimentions": "Wymiary",
"Width": "Szerokość",
"Height": "Wysokość",
"{0} pixels": "{0} <'{0}' == '1' ? 'piksel' : ('{0}'.endsWith('5') || '{0}'.endsWith('6') || '{0}'.endsWith('7') || '{0}'.endsWith('8') || '{0}'.endsWith('9') || '{0}' == '12' || '{0}' == '13' || '{0}' == '14' ? 'pikseli' : 'piksele')>",
"I couldn't find the requested information.": "Nie mogłem znaleźć żądanej informacji.",
"Author": "Autor",
"by {0}": "przez {0}",
"commander of this package decided to unpublish it.": "autor tego pakietu zdecydował go usunąć.",
"Image information requested by {0}": "Informacje o obrazie żądane przez {0}",
"Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "Wybierz numer pomiędzy 1 a {0} (za jedną minutę komenda zostanie odwołana)",
"Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown": 
"W ciągu następnych 30 sekund, musisz wybrać numer między 1 a {0}. Komenda zostanie automatycznie zatrzymana w ciągu 30 sekund, jeśli wybór nie został wykonany. Alternatywnie wpisz `cancel`, żeby ręcznie zatrzymać komendę, omijając czasomierz.",
"Progress": "Postęp",
"Requested by {0}": "Żądane przez {0}",
"I think it may work better if you are in a voice channel!": "Myślę, że to zadziała lepiej, jeśli będziesz w kanale głosowym...",
"Now Playing: {0}": "Teraz gramy: {0}",
"there isn't any music playing. :P": "żadna muzyka nie gra. :P",
"I have successfully paused {0}.": "Szczęśliwie zatrzymałem {0}.",
"Examples": "Przykłady",
"Aliases": "Pseudonimy", 
"Permissions": "Uprawnienia",
"Category": "Kategoria",
"Help for command \"{0}\"": "Pomoc dla komendy \"{0}\"",
'To view a list of all the commands, go to the [Yamamura Website Command Page]({0}).': "Żeby zobaczyć listę wszystkich komend, przyjdź na [stronę komend strony bota Yamamura]({0}).",
"To view a list of a command of a specific category, type `{0}commands (category name)`.": "Żeby zobaczyć listę komend specyficznej kategorii, wpisz `{0}commands (nazwa kategorii)`",
"Command Listing": "Lista Komend",
"{0}ms": "{0}ms",
"The message round-trip took {0}": "Wysłanie wiadomości w obie strony trwało {0}",
"The heartbeat ping is {0}": 'Ping "bicie serca :heart:" trwał {0}',
"Welcome to {0}": "Witamy do {0}",
"This is a discord bot made in Discord-Akairo written for MakerBoard connectivity.": "To jest bot Discord-owy stworzony w Discord-Akairo stworzonym przez społeczność MakerBoard",
"If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Jeśli chcesz zobaczyć wszystkie dostępne komendy, proszę sprawdzić naszą stronę, lub wpisać {0}commands",
"Publicity": "Publiczność",
}