module.exports = {
	// MARK: General purpose
	"Type `cancel` to cancel this command.": "Напишите `cancel`, чтобы отменить эту команду.",
	"by {0}": "от {0}",
	"There are not enough arguments to this command. The minimum is {0}.": "Не хватает аргументов для этой команди. Минимум это {0}.",

	// MARK: Commands command
	"No description available.": "Нету описание.",
	"Total Commands: {0}": "Количество команд: {0}",

	"Progress": "Прогресс",
	"Examples": "Примеры",
	"Aliases": "Псевдоними",
	"Permissions": "Права",
	"Category": "Категория",
	'Help for command "{0}"': 'Помощь для команды "{0}"',
	'To view a list of all the commands, please go to our website\'s command page: {0}': "Чтобы просмотреть список всех команд, перейдите на список команд на нашем сайте: {0}.",
	"To view a list of a command of a specific category, type `{0}commands (category name)`.": "Чтобы просмотреть список команд спецефичной категории, напишите `{0}commands (категория)`",
	"Command Listing": "Список команд",

    // MARK: Imginfo command
    "Format": "Формат",
    "Dimentions": "Размеры",
    "Width": "Ширина",
    "Height": "Высота",
    "{0} pixels": "{0} пикселей",
	"Image information requested by {0}": "Информация про изображения, запрошенная {0}",

    // MARK: Lang command
    "The language has been changed to {0} **{1}**.": "Язык был сменен на {0} **{1}**.",
    "Which language would you like to set? \nHere is a list of the available languages:": "Какой Вы хотите выбрать язык? \nВот список всех доступних языков:",
    "That is an invalid language. Here are the available languages:": "Это неверный язык. Вот доступные языки:",

    "I couldn't find the requested information.": "Я не мог найти информацию, которую вы запросили.",
    "Author": "Автор",
    "commander of this package decided to unpublish it.": "Командир этого пакета решил отменить его публикацию.",
	"Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "Выберете число от 1 к {0} (через 1 минуту, команда будет отменена)",
    "Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown": "За следующих 30 секунд, вам нужно будет выбрать число от 1 к {0}. Команда будет автоматически отменена за 30 секунд, если не было выбора. Альтернативно, напишите `cancel` чтобы отменить команду вручную, пропуская отчет.",
    "{0}ms": "{0}ms",
    "The message round-trip took {0}": "Сообщение туда-назад заняло {0}",
    "The heartbeat ping is {0}": "Пинг сердцебиение - {0}",
    "Welcome to {0}": "Добро пожаловать в {0}",
    "If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Чтобы просмотреть команди, пожалуста посмотрите на сайте, либо напишите {0}commands",
    "Publicity": "Публичность",
    "Usage": "Использование",
    "Resource Usage": "Исползование ресурсов",
    "Backends": "Бэкенды",
    "Database System": "Система базы данных",
    "day": "сутка",
    "days": "суток",
    "hour": "час",
    "hours": "часов",
    "minute": "минута",
    "minutes": "минут",
    "second": "секунда",
    "seconds": "секунд",
    "and": "и",
    "ago": "назад",
    "Uptime": "Провел",
    "Creation date": "Дата создание",
    "Total Events": "Все мероприятия",
	"{0} total commands": "{0} команд",
	"{0} total listeners": "{0} слушителей",
	"You didn't specify a key!": "Вы не выбрали числа!",
	"You didn't specify a value!": "Вы не вибрали значение!",
	"Are you ___**100%**___ sure you want to reset the configuration? [Y/N]": "Вы ___**100%**___ уверини, что хотите сделать сброс конфигурации? [Y (да)/N (нет)]",
	"action cancelled": "действие отменено",
	"There's no `{0}` key in the configuration!": "Нету числа `{0}` в конфигурации!",
	"There has been an error while clearing the configuration. Please report this bug to the {0} Developers": "Была ошибка с очисткой конфигурации. Пожалуйста, объясните это с авторами {0}",
	"{0} - by {1}": "{0} - на {1}",
	"An error occurred: {0}.\nAlert the bot owners to let them fix this error": "Была ошибка: {0}.\nОбъясните об этом авторам бота, чтобы оны её исправили ",
	"There's no type with ID `{0}`": "Нету типа с ID `{0}`",
    "The action must be one of [{0}]!": "Действие должно быть одно из [{0}]!",
    "Server configuration for {0}": "Серверная конфигурация для {0}",
	"This value is empty": "Это значение пусто",
	"You can use `{0}config set <key> null` to set a value to an empty state.": "Вы можете исползовать `{0}config set <число> null` чтобы позначить значение как пустое.",
	"The input `{0}` is not valid for the type `{1}`.": "Значение `{0}` не верное для `{1}`",
	"Administration": "Администрация",
	"Experience Points": "Опыт",
	"Games": "Игры",
	"MakerBoard Connectivity": "Соеднение с MakerBoard",
	"Useful": "Полезное",
	"Audio": "Аудио",
	"Fun": "Весёлое",
	"Image Edits": "Изминение изображений",
	"Moderation": "Модерация",
	"Bot Utilities": "Утилиты бота",
	"Game Server Statistics": "Статистика игрового сервера",
	"Text Edits": "Изминение текста",
	"View and set your server's config for the bot.": "Просмотреть и настройте бота на конфигурацию вашого сервера.",
	"Log channel": "Канал лога",
	"Welcome channel": "Канал о пожалование добра",
	"Welcome messages": "Сообщение о пожалувание добра",
	"Leave message": "Сообщение о уходе",
	"Prefix": "Префикс",
	"MakerBoard URL": "URL MakerBoard`а",
	"Starboard channel": "Канал Starboard",
	"Level UP messages": "Сообщение о подвышение уровня",
	"Level UP": "Повышение уровня",
    "Muted role": "Роль заткунувшего",
    "You need to have the configuration key `mutedrole` set in order for this command to work.": "Вы должни наставить конфигурацейный ключ `mutedrole` чтобы использовать эту команду.",
    "The user you wanted to mute needs to be in this server in order for this command to work.": "Пользователь, которого вы хотите заткнуть, должен быть в этом сервере.",
    "Administrators can't be muted. It wouldn't affect them.": "Администраторов нельзя заткнуть. Это не повлияет на них.",
    "You need to have the `Administrator` permission in order to mute moderators.": "Вы должни иметь роль `Администратор` чтобы заткнуть модератора.",
    "You can't mute someone who has a higher role position than you.": "Вы не можете заткнуть того, кто имеет роль вышу за вашу.",
    "You can't mute yourself!": "Вы не можете заткнуть себя!",
    "{0} was successfully muted": "{0} был успешно заткнут.",
    "{0} was successfully unmuted": "{0} был успешно разткнут.", 
    "an error occured while trying to mute the user. Report this error to the Yamamura developers: `{0}`": "была ошыбка при затыкание этого пользователя. Оповестите эту ошыбку авторам Yamamura: `{0}`",
    "Enabled": "Включено",
    "Disabled": "Выключено",

    "Requested by {0}": "Запрос от {0}",
    "I have successfully paused {0}.": "Я успешно приостановил плеер {0}.",
    "I think it may work better if you are in a voice channel!": "Я думаю, что будет лучше если вы в голосовом канале.",
    "Now Playing: {0}": "Сейчас играет: {0}",

    "there currently isn't any music playing in this server.": "Сейчас нету музыки, которая играет в этом сервере.",
    "I have successfully cleared the configuration": "Я успешно очистил конфигурацию.",
    "I couldn't get text to mock.": "Я не нашёл текст, из которого издеваться.",
    "There was no text I can find to convert to hexadecimal.": "Не было тексту, которого я мог бы переработать в шестнадцатеричный .",
    'There was no Bs found in the text': "Я не нашёл буков `B` в тексте",
    "Related Videos": 'Связанные видео',
    "in order to pause audio, there needs to be audio playing in the channel": 'Чтобы запаузить музыку, она должна играть в голосовом канале.',
    "in order to resume audio, there needs to be audio playing in the channel": 'Чтобы продолжыть музыку, она должна играть в голосовом канале.',
    'Pause the currently playing audio.': 'Запаузить музыку которая сейчас играет.',
    'Shows information on the currently playing song.': 'Показать информацию про музыку, которая сейчас играет',
    'Plays the audio of a Youtube video.': 'Играет музыку из видео YouTube.',
    'Please state a song from Youtube you\'d like to listen to': 'Пожалуста назвите музыку из YouTube, которую вы хотите послушать',
    'That\'s not a valid song! Try again.': 'Это неверная песня! Попробуйте ещё раз.',
    'Shows the music queue for the current server.': 'Показывает очередь музыкы для даного сервера.',
	"you need to be in a voice channel in order for me to play music": "Вы должны быть в голосовом канале чтобы я играл музыку",
	"You lost perms to connect to the Voice Channel.": "Вы утеряли права, чтобы подключится к голосовом канале.",
	"I can't join. Make sure I have the proper permissions.": "Я не могу присоеднится к голосовом канале. Подтвердите, что у меня верные права.",
	"I can't speak. Make sure I have the proper permissions.": "Я не могу разговаревать. Подтвердите, что у меня верные права.",
	"Related Music Search": "Поиск связанной музыкы",
	"Added {0} song(s) to Queue: {1} | Requested by: {2}": "Добавил {0} песень к очереди: {1} | Запрошен: {2}",
	"Aggiunto alla coda: {0} | Richiesto da: {1}": "",
	"**NOW PLAYING**: [{0}]({1}) | Requested by {2}": "**СЕЙЧАС ИГРАЕТ**: [{0}]({1}) | Запрошен {2}",
	"**NEXT**: [{0}]({1}) | Requested by {2}": "**СЛЕДУЮЩИЙ**: [{0}]({1}) | Запрошен {2}",
	"{0} Users": "{0} Изпользователёв",
	"{0} Channels": "{0} Каналов",
    "{0} Servers": "{0} Серверов",
    "Resume the currently paused audio": "Продолжыть музыку, которую вы остановили"
    
    "Stops the music": "Остановляет музыку"
    "Yamamura - by NightYoshi370 & Samplasion": "Yamamura - от NightYoshi370 и Samplasion"
    "It can fulfill your server's moderation needs and create fun events for your community to enjoy": "Он может надать вам вашые требования модерации и создавать для вашего сообщества ивенты и игры" //Damn this was hard to translate along with the next line.
    "Yamamura is an all-in-one Discord bot dedicated to helping modding communities and more.": "Yamamura - это всё-в-одном Дискорд бот преданный помагать сообществам моддингу и болше."
    "Adds a vote to skip the currently playing music.": "Добавляет голос пропутить сейчас-играющюю музыку."
    "Give a server member a specified amount of points.": "Дать пользователю спецефичиское число очков."
    "List all those with the highest amount of points": "Показать всех с самым большым количеством очков"
    "Shows a user's experience points.": "Показывает количество очков пользователя."
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
};