export default {
	// MARK: General purpose
	"Type `cancel` to cancel this command.": "コマンドをキャンセルするには`cancel`を入力します",
	"by {0}": "- {0}さん",
	"Requested by {0}": "{0}さんによるリクエスト",
	"There are not enough arguments to this command. The minimum is {0}.": "このコマンドには十分な引数がありません。最小値は{0}です",
	"command canceled": "コマンドはキャンセルされました",
	"Command has been cancelled": "コマンドはキャンセルされました",
	"Too many retries, command has been cancelled.": "再試行が多すぎるため、コマンドはキャンセルされました",
	"Time ran out, command has been cancelled.": "時間切れ、コマンドはキャンセルされました",

	// MARK: pick
	"What items would you like to pick from?": "どのアイテムから選びますか？",
	"Type them in separate messages.": "別のメッセージに入力してください。",
	"Type stop when you are done.": "完了したか、`stop`を入力します",

	// MARK: Categories
	"Audio": "オーディオ",
	"Bot Utilities": "ボットユーティリティ",
	"Covers": "カバー",
	"Experience Points": "経験値",
	"Fun": "楽しい",
	"Game Server Statistics": "ゲームサーバーの統計",
	"Games": "ゲーム",
	"Image Edits": "画像編集",
	"Server Management": "サーバー管理",
	"Text Fun": "テキストの楽しい",
	"Useful": "有用",

	// MARK: Audio category
	"Shows information on the currently playing song.": "現在再生中の曲に関する情報を表示します",
	"Pause the currently playing audio.": "現在再生中のオーディオを一時停止する",
	"Plays the audio of a Youtube video.": "YouTubeビデオのオーディオを再生します",
	"Shows the music queue for the current server.": "現在のサーバーのミュージックキューを表示します",
	"Resume the currently paused audio.": "現在再生中のオーディオを再開する",
	"Adds a vote to skip the currently playing music.": "現在再生中のミュージックをスキップする投票を追加します",
	"Stops the music.": "ミュージックを止める",

	"I have successfully resumed {0}.": "{0}を再開しました",
	"I have successfully paused {0}.": "{0}を一時停止しました",
	"I think it may work better if you are in a voice channel!": "ボイスチャンネルにいればもっとうまくいくと思います！",
	"Now Playing: {0}": "再生中：{0}",

	"**NOW PLAYING**: [{0}]({1}) | Requested by {2}": "**再生中**：[{0}]({1}) | {2}さんによるリクエスト",
	"**NEXT**: [{0}]({1}) | Requested by {2}": "**次**：[{0}]({1}) | {2}さんによるリクエスト",

	"Music Search": "ミュージック検索",

	// MARK: Bot utilites category
	"Invite Bot": "ボットを招待",
	"Website": "Webサイト",
	"Commands": "コマンド",
	"Support Server": "サポートサーバー",

	// MARK: Experiece points category
	"Give a server member a specified amount of points.": "サーバーメンバーに指定された量の経験値を与えます",
	"List all those with the highest amount of points": "最高ポイントの人をリストする",
	"Shows a user's experience points.": "ユーザーの経験値を表示する",
	"bots do not collect Experience Points! Please try this command on a different user": "ボットは経験値を収集しません！別のユーザーでこのコマンドを試してください",
	"Yamamura is not in that server. Therefore, I cannot get that server's points": "Yamamuraはそのサーバーにはいません。したがって、そのサーバーのポイントを取得できません",
	"you may not see the statistics of a server you are not in. Try again later": "あなたがメンバーしていないサーバーの統計が表示されない場合があります。別のサーバーでもう一度お試しください",
	"you can't see the points of a user who is/was not in the server. Please try again on a different user.": "サーバーにいないユーザーのポイントを見ることができません。別のユーザーでもう一度お試しください",

	"This field contains the user you'd like to give server points too. This can either be a mention, username or user ID": "このフィールドには、サーバーポイントを付与するユーザーが含まれます。これは、メンション、ユーザー名、またはユーザーIDのいずれかです", // To
	"Who would you like to donate points to?": "誰にポイントを寄付しますか？",
	"That's not something we can give points to! Try again.": "それはポイントを与えることができるものではありません！再試行する",
	"This argument is the amount of points you'd like to donate to the user.": "これはユーザーに寄付したいポイントの量です。",
	"How many points would you like to donate?": "何点寄付しますか？",
	"That's an invalid amount of points! Try again": "それは無効なポイントです！ 再試行する",
	"This argument is for the guild ID you'd like your transactions to go through. Will default itself to the guild ID of the current server if its on a server.": "これはトランザクションを通過させたいギルドID用です。現在のサーバーのギルドIDにデフォルトで設定されます",
	"This is the action you will perform for the user. It can be either adding, setting or removing": "これはユーザーに対して実行するアクションです。追加、設定、または削除できます",
	"Used by bot owners to override bot limits": "ボットの制限を無効にするためにボットの所有者が使用します",
	"you can't give points to someone who is/was not in the server. Please try again on a different user.": "サーバーにいないユーザーにポイント与えることはできません。別のユーザーでもう一度お試しください",
	"you would not benefit from that.": "あなたはそれから利益を得ないでしょう",
	"you may not steal points!": "あなたはポイントを盗むことはできません！",
	"You do not have enough points to donate to the user! Please try again once you collect more points": "あなたはそのユーザーに寄付するのに十分なポイントがありません！さらにポイントを集めてからもう一度お試しください",
	"thank you so much for donating {0} points to {1}. They are now at level {2}": "{0}ポイントを{1}に寄付していただき、ありがとうございます。{1}はレベル{2}になりました",
	"\n Unfortunately, that also means you're now down to {0} points, and are now at level {1}": "\n残念ながら、それはまたあなたが{0}ポイントとレベル{1}になり",

	"Leaderboard for {0}": "{0}のリーダーボード",
	"Handled by Yamamura": "Yamamuraが操作",
	"Top {0} posters": "上位{0}ユーザー",
	"**{0}. {1}: {2} points (level {3}) \n": "**{0}. {1}：{2}ポイント（レベル{3}）\n",
	" Leaderboard - Top {0}": "のリーダボート - 上位{0}",
	"Yamamura Leaderboard": "Yamamuraのリーダーボード",
	"{0} ({1} points)": "{0}（{1}ポイント）",

	"Points system handled by Yamamura": "Yamamuraがポイントシステムを操作",
	"Points": "ポイント",
	"Level": "レベル",
	"There's no higher level that this user can reach. This user is already at their maximum level possible.": "このユーザーが到達できるより高いレベルはありません。このユーザーはすでに可能な最大レベルに達しています。",
	"{0} more points until level up!": "さらに{0}ポイントでレベルアップ！",
	"{0} is currently standing at level {1} with {2} points.": "{0}さんは現在、{2}ポイントでレベル{1}です",
	"Showing stats for {0}": "{0}の統計を表示しています",
	"we do not share any servers with this user. Please try again with a different user.": "このユーザーとサーバーを共有しません。 別のユーザーでもう一度お試しください",

	// MARK: Lang command
	"The language has been changed to {0} **{1}**.": "言語が{0}**{1}**に変更されました",
	"Which language would you like to set? \nHere is a list of the available languages:": "どの言語を設定しますか？\n利用可能な言語のリストは次のとおりです：",
	"That is an invalid language. Here are the available languages:": "それは無効な言語です。利用可能な言語のリストは次のとおりです：",

	// MARK: Commands command
	"No description available.": "説明はありません",
	"Total Commands: {0}": "合計コマンド：{0}",

	// MARK: Imginfo command
	"Format Extention": "フォーマットの拡張子", // Extension
	"Dimentions": "大きさ",
	"Width": "幅",
	"Height": "高さ",
	"{0} pixels": "{0}ピクセル",

	// MARK: Time
	"day": "日",
	"days": "日",
	"hour": "時間",
	"hours": "時間",
	"minute": "分",
	"minutes": "分",
	"second": "秒",
	"seconds": "秒",
	"and": "と", // Is this related to time?
	"ago": "前",
	"Uptime": "稼働時間",
	"Creation date": "作成日",

	// MARK: Other
	"I couldn't find the requested information.": "要求された情報が見つかりませんでした",
	"Author": "著者",
	"commander of this package decided to unpublish it.": "パッケージの作成者が発行をキャンセルすることを決定しました",
	"Image information requested by {0}": "{0}さんによる要求された画像情報",
	"Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "1〜{0}の番号を選択します（1分後にコマンドはキャンセルされます）",
	"Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made.Alternatively, type `cancel` to manually cancel the command, skipping the countdown": "次の30秒以内に、1〜{0}の間の数値を選択する必要があります。選択が行われなかった場合、コマンドは30秒後に自動的にキャンセルされます。",
	"Progress": "プログレス",
	"Examples": "例",
	"Aliases": "エリアス",
	"Permissions": "パーミッション",
	"Category": "カテゴリー",
	"Help for command \"{0}\"": "コマンド「{0}」のヘルプ",
	"To view a list of all the commands, please go to our website's command page: {0}": "すべてのコマンドのリストを表示するには、Webサイトのコマンドページにアクセスしてください：{0}",
	"To view a list of a command of a specific category, type `{0}commands (category name)`.": "カテゴリーのコマンドのリストを表示するには、`{0}commands (カテゴリー名)`を入力します",
	"Command Listing": "コマンドリスト",
	"{0}ms": "{0}ms",
	"The message round-trip took {0}": "メッセージの往復にが{0}かかりました",
	"The heartbeat ping is {0}": "ハートビートピングは{0}です",
	"Welcome to {0}": "{0}へようこそ",
	"{0} is an all-in-one Discord bot dedicated to helping modding communities and more.": "{0}はコミュニティの改造などを支援するオールインワンのDiscordボットです",
	"It can fulfill your server's moderation needs and create fun events for your community to enjoy": "サーバーのモデレートのニーズを満たし、コミュニティが楽しめる楽しいイベントを作成できます",
	"If you'd like to see all the available commands, please take a look at our website or type {0}commands": "利用可能なすべてのコマンドを表示するには、Webサイトにアクセスか、`{0}commands`を入力してください",
	"Links": "リンク",
	"Publicity": "宣伝",
	"Usage": "使用法",
	"Resource Usage": "リソース使用量",
	"Backends": "バックエンド",
	"Database System": "データベースシステム",
	"Total Events": "合計イベント",
	"{0} total commands": "合計{0}コマンド",
	"{0} total listeners": "合計{0}リスナー",
	"You didn't specify a key!": "キーを指定しませんでした！",
	"You didn't specify a value!": "値を指定しませんでした！",
	"Are you ___**100%**___ sure you want to reset the configuration? [Y/N]": "設定をリセットしてもよろしいですか？ [Y (はい) / N (いいえ)]",
	"action cancelled": "キャンセルされたアクション",
	"There's no `{0}` key in the configuration!": "設定に`{0}`キーがありません！",
	"There has been an error while clearing the configuration. Please report this bug to the {0} Developers": "設定のクリア中にエラーが発生しました。このバグを{0}開発者に報告してください",
	"{0} - by {1}": "{1}さんによる{0}",
	"An error occurred: {0}.\nAlert the bot owners to let them fix this error": "エラーが発生しました：{0}\nこのエラーを修正できるように、ボットの所有者に報告してください",
	"There's no type with ID `{0}`": "ID `{0}`のタイプはありません",
	"The action must be one of [{0}]!": "アクションは[{0}]のいずれかでなければなりません！",
	"Server configuration for {0}": "{0}のサーバーの設定",
	"This value is empty": "この値は空です",
	"You can use `{0}config set <key> null` to set a value to an empty state.": "`{0}config set <キー> null`を使用して、値を空の状態に設定できます",
	"The input `{0}` is not valid for the type `{1}`.": "入力`{0}`はタイプ`{1}`には無効です",
	"{0}'s Command Listing": "{0}のコマンドリスト",
	"Category listing: {0}": "カテゴリーリスト：{0}",
	"View and set your server's config for the bot.": "サーバーのボットの設定を表示と設定します",
	"Log channel": "ログチャンネル",
	"Welcome channel": "ようこそチャンネル",
	"Welcome messages": "ようこそメッセージ",
	"Leave message": "去るメッセージ",
	"Prefix": "プレフィックス",
	"MakerBoard URL": "MakerBoard URL",
	"Starboard channel": "Starboardチャンネル",
	"Level UP messages": "レベルアップメッセージ",
	"Level UP": "レベルアップ",
	"Muted role": "ミュートされた役割",
	"You need to have the configuration key `mutedrole` set in order for this command to work.": "このコマンドが機能するには、設定キー`mutedrole`を設定する必要があります",
	"The user you wanted to mute needs to be in this server in order for this command to work.": "このコマンドが機能するには、ミュートするユーザーがこのサーバーにいる必要があります",
	"Administrators can't be muted. It wouldn't affect them.": "管理者をミュートすることはできません。彼らには影響しません",
	"You need to have the `Administrator` permission in order to mute moderators.": "モデレーターをミュートするには、`管理者`権限が必要です",
	"You can't mute someone who has a higher role position than you.": "自分よりも高役割を持つ人をミュートすることはできません",
	"You can't mute yourself!": "自分をミュートすることはできません",
	"{0} was successfully muted": "{0}は正常にミュートされました",
	"{0} was successfully unmuted": "{0}は正常にミュート解除されました",
	"an error occured while trying to mute the user. Report this error to the Yamamura developers: `{0}`": "ユーザをミュートしようとしたときにエラーがしっ発生しました。このエラーをYamamuraの開発者に報告してください",
	"Enabled": "オン",
	"Disabled": "オフ",

	"there currently isn't any music playing in this server.": "現在、このサーバーで再生しているミュージックはありません",
	"I have successfully cleared the configuration": "設定を正常にクリアしました",
	"I couldn't get text to mock.": "モックへのテキストを取得できませんでした",
	"There were no text I can find to convert to hexadecimal.": "16進数に変換するテキストが見つかりませんでした",
	"There was no Bs found in the text": "テキストに「B」が見つかりませんでした",
	"Related Videos": "関連動画",
	"in order to pause audio, there needs to be audio playing in the channel": "オーディオを一時停止するには、チャンネルでオーディオを再生する必要があります",
	"in order to resume audio, there needs to be audio playing in the channel": "オーディオを再開するには、チャンネルでオーディオを再生する必要があります",
	"Please state a song from Youtube you'd like to listen to": "Youtubeから聴きたい曲を入力してください",
	"That's not a valid song! Try again.": "これは有効な曲ではありません！再試行する",
	"you need to be in a voice channel in order for me to play music": "私がミュージックを再生するためには、あなたにはボイスチャンネルにいる必要があります",
	"You lost perms to connect to the Voice Channel.": "ボイスチャンネルに接続する権限を失いました",
	"I can't join. Make sure I have the proper permissions.": "参加できません。適切な権限があることを確認してください",
	"I can't speak. Make sure I have the proper permissions.": "話せません。適切な権限があることを確認してください",
	"Related Music Search": "関連ミュージック検索",
	"Added {0} song(s) to Queue: {1} | Requested by: {2}": "{0}曲が{1}キューを追加されました | {2}さんによるリクエスト",
	"Aggiunto alla coda: {0} | Richiesto da: {1}": "",
	"{0} Users": "{0}ユーザー",
	"{0} Channels": "{0}チャンネル",
	"{0} Servers": "{0}サーバー",
};