module.exports = {
  'No description available.': "Nessuna descrizione",
  "Total Commands: {0}": "Comandi disponibili: {0}",
  "There are not enough arguments to this command. The minimum is {0}.": "Non ci sono abbastanza argomenti per questo comando. Il minimo è {0}.",
  "The language has been changed to {0} **{1}**.": "La lingua è stata cambiata in {0} **{1}**.",
  "Format": "Formato",
  "Dimentions": "Dimensioni",
  "Width": "Larghezza",
  "Height": "Altezza",
  "{0} pixels": "{0} pixel",
  "I couldn't find the requested information.": "Non ho potuto trovare le informazioni richieste.",
  "Author": "Autore",
  "by {0}": "di {0}",
  "commander of this package decided to unpublish it.": "l'autore del pacchetto ha deciso di annullarne la pubblicazione.",
  "Image information requested by {0}": "Informazioni sull'immagine richieste da {0}",
  "Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "Scegli un numero tra 1 e {0} (in un minuto il comando verrà annullato)",
  "Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown": 
    "Entro i prossimi 30 secondi, dovrai scegliere un numero compreso tra 1 e {0}. Il comando verrà automaticamente annullato tra 30 secondi se non sarà stato scelto nessun brano. In alternativa, puoi scrivere `cancel` per annullare il comando, saltando il countdown.",
  "Progress": "Progresso",
  "Requested by {0}": "Richiesto da {0}",
  "I think it may work better if you are in a voice channel!": "Credo funzionerebbe meglio se tu fossi in un canale vocale.",
  "Now Playing: {0}": "In riproduzione: {0}",
  "there isn't any music playing. :P": "non c'è niente in riproduzione. :P",
  "I have successfully paused {0}.": "Ho messo in pausa {0}.",
  "Examples": "Esempi",
  "Aliases": "Alias", 
  "Permissions": "Permessi",
  "Category": "Categoria",
  "Help for command \"{0}\"": "Aiuto per il comando \"{0}\"",
  'To view a list of all the commands, go to the [Yamamura Website Command Page]({0}).': "Per vedere una lista di tutti i comandi, vai alla [pagina dei comandi sul sito di Yamamura]({0}).",
  "To view a list of a command of a specific category, type `{0}commands (category name)`.": "Per vedere una lista di comandi appartenenti ad una specifica categoria, digita `{0}commands (nome categoria)`",
  "Command Listing": "Lista Comandi",
  "{0}ms": "{0}ms",
  "The message round-trip took {0}": "L'invio del messaggio andata e ritorno ha impiegato {0}",
  "The heartbeat ping is {0}": "Il ping heartbeat è {0}",
  "Welcome to {0}": "Benvenuto a {0}",
  "This is a discord bot made in Discord-Akairo written for MakerBoard connectivity.": "Questo è un bot Discord creato in Discord-Akairo per la connettività con Makerboard",
  "If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Per vedere tutti i comandi, dai un'occhiata alla nostra pagina web o digita {0}commands",
  "Publicity": "Pubblicità",
  "Usage": "Utilizzo",
  "Resource Usage": "Utilizzo Risorse",
  "Backends": "Backend",
  "Database System": "Database",
  "day": "giorno",
  "days": "giorni",
  "hour": "ora",
  "hours": "ore",
  "minute": "minuto",
  "minutes": "minuti",
  "second": "secondo",
  "seconds": "secondi",
  "and": "e",
  "ago": "fa",
  "Uptime": "Tempo di attività",
  "Creation date": "Data di creazione",
  "Total Events": "Eventi",
  "{0} total commands": "{0} comandi",
  "{0} total listeners": "{0} azioni assegnate ad eventi", // Woah, this is really hard to translate ~Samplasion
  "You didn't specify a key!": "Non hai specificato una chiave!",
  "You didn't specify a value!": "Non hai specificato un valore!",
  "Are you ___**100%**___ sure you want to reset the configuration? [Y/N]": "Sei sicuro al ___**100%**___ di voler ripristinare la configurazione? [Y (sì)/N (no)]",
  "action cancelled": "azione annullata",
  "There's no `{0}` key in the configuration!": "Non c'è alcuna chiave `{0}` nella configurazione!",
  "I have successfully cleared the configuration": "",
  "There has been an error with the configuration clearance. Please report this bug to the {0} Developers": "Si è verificato un errore durante il ripristino della configurazione. Riporta il bug agli sviluppatori di {0}",
  "{0} - by {1}": "{0} - di {1}",
  "An error occurred: {0}.\nAlert the bot owners to let them fix this error": "Si è verificato un errore: {0}.\nAvvisa gli sviluppatori per far correggere questo errore", 
  "There's no type with ID `{0}`": "Non esiste alcun tipo con ID `{0}`",
  "The action must be one of [{0}]!": "L'azione deve essere una di [{0}]!",
  "Server configuration for {0}": "Configurazizone del server {0}",
  "This value is empty": "Questo valore è vuoto",
  "You can use `{0}config set <key> null` to set a value to an empty state.": "Usa `{0}config set <chiave> null` per impostare un valore su vuoto.",
  "The input `{0}` is not valid for the type `{1}`.": "Il valore `{0}` non è valido per il tipo `{1}`",
  "Administration": "Amministrazione",
  "Experience Points": "Punti Esperienza",
  "Games": "Giochi",
  "MakerBoard Connectivity": "Connettività a MakerBoard",
  "Useful": "Utility",
  "Audio": "Audio",
  "Fun": "Divertimento",
  "Image Edits": "Modifiche di immagini", // Not final. At all ~Samplasion
  "Moderation": "Moderazione",
  "Bot Utilities": "Utility del bot",
  "Game Server Statistics": "Statistiche server di gioco",
  "Image Fun": "Divertimento con le immagini", // Not final. At all ~Samplasion
  "Text Edits": "Modifiche del testo",
  "View and set your server's config for the bot.": "Visualizza e modifica la configurazione del server per il bot.",
  "Log channel": "Canale di log",
  "Welcome channel": "Canale di benvenuto",
  "Welcome messages": "Messaggi di benvenuto",
  "Leave message": "Messaggio di abbandono",
  "Prefix": "Prefisso",
  "MakerBoard URL": "URL MakerBoard",
  "Starboard channel": "Canale Starboard",
  "Level UP messages": "Messaggi di level UP",
  "Level UP": "Level UP",
  "You need to have the configuration key `mutedrole` set in order for this command to work.": "Perché questo comando possa funzionare, la chiave di configurazione `mutedrole` deve essere impostata."
}