module.exports = {
	// MARK: General purpose
	"Type `cancel` to cancel this command.": "Scrivi `cancel` (annulla) per annullare il comando.",
	"by {0}": "di {0}",
    "There are not enough arguments to this command. The minimum is {0}.": "Non ci sono abbastanza argomenti per questo comando. Il minimo è {0}.",
    "Time ran out, command has been cancelled.": "Tempo scaduto; il comando è stato annullato.",
    "Too many retries, command has been cancelled.": "Troppi tentativi; il comando è stato annullato.",
    "Command has been cancelled.": "Il comando è stato annullato.",
    "Progress": "Progresso",

    // MARK: General purpose - Audio
    "Now Playing: {0}": "In riproduzione: {0}",
	"**NOW PLAYING**: [{0}]({1}) | Requested by {2}": "**IN RIPRODUZIONE**: [{0}]({1}) | Richiesto da {2}",
	"**NEXT**: [{0}]({1}) | Requested by {2}": "**PROSSIMO**: [{0}]({1}) | Richiesto da {2}",
    "Requested by {0}": "Richiesto da {0}",

    // MARK: Nowplaying command
    "there currently isn't any music playing in this server.": "non c'è musica in riproduzione nel server in questo momento",

	// MARK: Commands command
	"No description available.": "Nessuna descrizione",
	"Total Commands: {0}": "Comandi disponibili: {0}",

	"Examples": "Esempi",
	"Aliases": "Alias",
	"Permissions": "Permessi",
	"Category": "Categoria",
	'Help for command "{0}"': 'Aiuto per il comando "{0}"',
	'To view a list of all the commands, please go to our website\'s command page: {0}': "Per vedere una lista di tutti i comandi, vai sul nostro sito: {0}.",
	"To view a list of a command of a specific category, type `{0}commands (category name)`.": "Per vedere una lista di comandi appartenenti ad una specifica categoria, digita `{0}commands (nome categoria)`",
	"Command Listing": "Lista Comandi",

    // MARK: Imginfo command
    "Format": "Formato",
    "Dimentions": "Dimensioni",
    "Width": "Larghezza",
    "Height": "Altezza",
    "{0} pixels": "{0} pixel",
	"Image information requested by {0}": "Informazioni sull'immagine richieste da {0}",

    // MARK: Lang command
    "The language has been changed to {0} **{1}**.": "La lingua è stata cambiata in {0} **{1}**.",
    "Which language would you like to set? \nHere is a list of the available languages:": "Che lingua vorresti impostare? \nEcco una lista di lingue disponibili:",
    "That is an invalid language. Here are the available languages:": "Quella non è una lingua valida. Ecco le lingue disponibili:",

    "I couldn't find the requested information.": "Non ho potuto trovare le informazioni richieste.",
    "Author": "Autore",
    "commander of this package decided to unpublish it.": "l'autore del pacchetto ha deciso di annullarne la pubblicazione.",
	"Choose a number between 1-{0} (in 1 minute, the command will be canceled)": "Scegli un numero tra 1 e {0} (in un minuto il comando verrà annullato)",
    "Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown": "Entro i prossimi 30 secondi, dovrai scegliere un numero compreso tra 1 e {0}. Il comando verrà automaticamente annullato tra 30 secondi se non sarà stato scelto nessun brano. In alternativa, puoi scrivere `cancel` per annullare il comando, saltando il countdown.",
    "{0}ms": "{0}ms",
    "The message round-trip took {0}": "L'invio del messaggio andata e ritorno ha impiegato {0}",
    "The heartbeat ping is {0}": "Il ping heartbeat è {0}",
    "Welcome to {0}": "Benvenuto a {0}",
    "If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Per vedere tutti i comandi, dai un'occhiata alla nostra pagina web o digita {0}commands",
    "Publicity": "Pubblicità",
    "Usage": "Utilizzo",
    "Resource Usage": "Utilizzo Risorse",
    "Backends": "Backend",
    "Database System": "Database",
    "day": "giorno",
    "days": "giorni",
    "hour": "ora",
    "hours": "ore",
    "minute": "minuto",
    "minutes": "minuti",
    "second": "secondo",
    "seconds": "secondi",
    "and": "e",
    "ago": "fa",
    "Uptime": "Tempo di attività",
    "Creation date": "Data di creazione",
    "Total Events": "Eventi",
	"{0} total commands": "{0} comandi",
	"{0} total listeners": "{0} azioni assegnate ad eventi", // Woah, this is really hard to translate ~Samplasion
	"You didn't specify a key!": "Non hai specificato una chiave!",
	"You didn't specify a value!": "Non hai specificato un valore!",
	"Are you ___**100%**___ sure you want to reset the configuration? [Y/N]": "Sei sicuro al ___**100%**___ di voler ripristinare la configurazione? [Y (sì)/N (no)]",
	"action cancelled": "azione annullata",
	"There's no `{0}` key in the configuration!": "Non c'è alcuna chiave `{0}` nella configurazione!",
	"There has been an error with the configuration clearance. Please report this bug to the {0} Developers": "Si è verificato un errore durante il ripristino della configurazione. Riporta il bug agli sviluppatori di {0}",
	"{0} - by {1}": "{0} - di {1}",
	"An error occurred: {0}.\nAlert the bot owners to let them fix this error": "Si è verificato un errore: {0}.\nAvvisa gli sviluppatori per far correggere questo errore",
	"There's no type with ID `{0}`": "Non esiste alcun tipo con ID `{0}`",
    "The action must be one of [{0}]!": "L'azione deve essere una di [{0}]!",
    "Server configuration for {0}": "Configurazizone del server {0}",
	"This value is empty": "Questo valore è vuoto",
	"You can use `{0}config set <key> null` to set a value to an empty state.": "Usa `{0}config set <chiave> null` per impostare un valore su vuoto.",
	"The input `{0}` is not valid for the type `{1}`.": "Il valore `{0}` non è valido per il tipo `{1}`",
	"Administration": "Amministrazione",
	"Experience Points": "Punti Esperienza",
	"Games": "Giochi",
	"MakerBoard Connectivity": "Connettività a MakerBoard",
	"Useful": "Utility",
	"Audio": "Audio",
	"Fun": "Divertimento",
	"Image Edits": "Immagini",
	"Moderation": "Moderazione",
	"Bot Utilities": "Utility del bot",
	"Game Server Statistics": "Statistiche server di gioco",
	"Text Edits": "Modifiche del testo",
	"View and set your server's config for the bot.": "Visualizza e modifica la configurazione del server per il bot.",
	"Log channel": "Canale di log",
	"Welcome channel": "Canale di benvenuto",
	"Welcome messages": "Messaggi di benvenuto",
	"Leave message": "Messaggio di abbandono",
	"Prefix": "Prefisso",
	"MakerBoard URL": "URL MakerBoard",
	"Starboard channel": "Canale Starboard",
	"Level UP messages": "Messaggi di level UP",
	"Level UP": "Level UP",
    "Muted role": "Ruolo silenziato",
    "You need to have the configuration key `mutedrole` set in order for this command to work.": "Perché questo comando possa funzionare, la chiave di configurazione `mutedrole` deve essere impostata.",
    "The user you wanted to mute needs to be in this server in order for this command to work.": "Perché questo comando possa funzionare, l'utente che hai provato a silenziare deve essere nel server.",
    "Administrators can't be muted. It wouldn't affect them.": "Gli amministratori non possono essere silenziati. Non avrebbe effetto.",
    "You need to have the `Administrator` permission in order to mute moderators.": "Devi avere il permesso di `Amministratore` per silenziare i moderatori.",
    "You can't mute someone who has a higher role position than you.": "Non puoi silenziare qualcuno che ha un ruolo con la posizione più alta della tua.",
    "You can't mute yourself!": "Non ti puoi silenziare da solo!",
    "{0} was successfully muted": "{0} è stato silenziato.",
    "{0} was successfully unmuted": "{0} può di nuovo parlare.",
    "an error occured while trying to mute the user. Report this error to the Yamamura developers: `{0}`": "si è verificato un errore mentre l'utente veniva silenziato. Avverti gli sviluppatori di Yamamura di questo errore: `{0}`",
    "Enabled": "Abilitato",
    "Disabled": "Non abilitato",

    "I have successfully paused {0}.": "Ho messo in pausa {0}.",
    "I think it may work better if you are in a voice channel!": "Credo funzionerebbe meglio se tu fossi in un canale vocale.",

    "I have successfully cleared the configuration": "Ho ripristinato la configurazione.",
    "I couldn't get text to mock.": "Non c'era testo da prendere in giro.",
    "There were no text I can find to convert to hexadecimal.": "Non c'era testo da convertire in esadecimale.",
    'There was no Bs found in the text': "Non c'erano B nel testo",
    "Related Videos": 'Video consigliati',
    "in order to pause audio, there needs to be audio playing in the channel": 'per mettere in pausa la musica, ci deve essere della musica in riproduzione nel server.',
    "in order to resume audio, there needs to be audio playing in the channel": 'per riprendere la musica, ci deve essere della musica in riproduzione nel server.',
    'Pause the currently playing audio.': 'Metti in  pausa la musica in riproduzione',
    'Shows information on the currently playing song.': 'Mostra informazioni sul brano in riproduzione',
    'Plays the audio of a Youtube video.': 'Riproduce un video di YouTube',
    'Please state a song from Youtube you\'d like to listen to': 'Inserisci un video di YouTube da riprodurre',
    'That\'s not a valid song! Try again.': 'Non è un brano valido! Riprova',
    'Shows the music queue for the current server.': 'Mostra la coda di riproduzione del server.',
	"you need to be in a voice channel in order for me to play music": "devi essere in un canale vocale prima di far partire la musica",
	"You lost perms to connect to the Voice Channel.": "Non hai il permesso di connetterti al Canale Vocale",
	"I can't join. Make sure I have the proper permissions.": "Non posso entrare. Assicurati che io abbia i permessi per farlo",
	"I can't speak. Make sure I have the proper permissions.": "Non posso parlare. Assicurati che io abbia i permessi per farlo",
	"Related Music Search": "Ricerca musica inerente",
	"Added {0} song(s) to Queue: {1} | Requested by: {2}": "Aggiunte {0} canzone/i alla Coda: {1} | Richiesto da: {2}",
	"Aggiunto alla coda: {0} | Richiesto da: {1}": "",
	"{0} Users": "{0} Utenti",
	"{0} Channels": "{0} Canali",
    "{0} Servers": "{0} Servers",

    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
};