const language = {
	// MARK: General purpose
	'Type `cancel` to cancel this command.': 'Scrivi `cancel` (annulla) per annullare il comando.',
	'by {0}': 'di {0}',
	'Requested by {0}': 'Richiesto da {0}',
	'There are not enough arguments to this command. The minimum is {0}.': 'Non ci sono abbastanza argomenti per questo comando. Il minimo è {0}.',
	'command canceled': 'comando annullato',
	'Command has been cancelled.': 'Il comando è stato annullato.',
	'Time ran out, command has been cancelled.': 'Tempo scaduto; il comando è stato annullato.',
	'Too many retries, command has been cancelled.': 'Troppi tentativi; il comando è stato annullato.',
	'{0} weather in {1}': 'Meteo a {1}: {0}',
  
	// MARK: General purpose - Audio
	'Shows information on the currently playing song.': 'Mostra informazioni sul brano in riproduzione.',
	'Pause the currently playing audio.': 'Mette in pausa il brano in riproduzione.',
	'Plays the audio of a Youtube video.': 'Invia alla coda un video di YouTube.',
	'Shows the music queue for the current server.': 'Mostra la coda di riproduzione del server.',
	'Resume the currently paused audio.': 'Riprende un brano in pausa.',
	'Adds a vote to skip the currently playing music.': 'Aggiunge un voto per saltare il brano in riproduzione.',
	'Stops the music.': 'Ferma la musica.',
  
	'I have successfully resumed {0}.': 'Ho messo in pausa{0}',
	'I have successfully paused {0}.': 'Ho ripreso {0}',
	'I think it may work better if you are in a voice channel!': 'Credo che funzionerebbe meglio se entrassi in un canale vocale...',
  
	'Now Playing: {0}': 'In riproduzione: {0}',
	'**NOW PLAYING**: [{0}]({1}) | Requested by {2}': '**IN RIPRODUZIONE**: [{0}]({1}) | Richiesto da {2}',
	'**NEXT**: [{0}]({1}) | Requested by {2}': '**PROSSIMO**: [{0}]({1}) | Richiesto da {2}',
	
	'Type `{0}play related` to play a related video': 'Scrivi `{0}play related` per avviare la riproduzione di un video correlato.',
	"Music Search": "Ricerca musicale",

	// MARK: Pick
	'What items would you like to pick from?': 'Da quali elementi vorresti effettuare la selezione?',
	'Type them in separate messages.': 'Scrivili in messaggi separati.',
	'Type stop when you are done.': 'Scrivi `stop` quando hai fatto.',
  
	// MARK: Categories
	Audio: 'Audio',
	'Bot Utilities': 'Utility del bot',
	Covers: 'Cover',
	'Experience Points': 'Punti esperienza',
	Fun: 'Svago', //? or "Divertimento"...?
	'Game Server Statistics': 'Statistiche di gioco',
	Games: 'Giochi',
	'Image Edits': 'Immagini divertenti', //! ugh
	'Server Management': 'Gestione server',
	'Text Fun': 'Testo divertente',
	Useful: 'Strumenti',
  
	// MARK: Nowplaying command
	"there currently isn't any music playing in this server.": "non c'è musica in riproduzione nel server in questo momento",
  
	// MARK: Pause command
	'in order to use audio commands, you will need to be in a voice channel': 'devi essere in un canale vocale per usare i comandi musicali',
	'in order to pause audio, there needs to be audio playing in the channel': 'devi essere in un canale vocale per poter mettere in pausa la musica',
	'the audio that you are currently supposed to be listening to is already paused': 'il brano che in teoria stai ascoltando è già in pausa',
  
	// MARK: Commands command
	'No description available.': 'Nessuna descrizione',
	'Total Commands: {0}': 'Comandi disponibili: {0}',
  
	Examples: 'Esempi',
	Aliases: 'Alias',
	Permissions: 'Permessi',
	Category: 'Categoria',
	'Help for command "{0}"': 'Aiuto per il comando "{0}"',
	'To view a list of all the commands, please go to our website\'s command page: {0}': 'Per vedere una lista di tutti i comandi, vai sul nostro sito: {0}.',
	'To view a list of a command of a specific category, type `{0}commands (category name)`.': 'Per vedere una lista di comandi appartenenti ad una specifica categoria, digita `{0}commands (nome categoria)`',
	'Command Listing': 'Lista Comandi',
  
	// MARK: Imginfo command
	Format: 'Formato',
	Dimentions: 'Dimensioni',
	Width: 'Larghezza',
	Height: 'Altezza',
	'{0} pixels': '{0} pixel',
	'Image information requested by {0}': "Informazioni sull'immagine richieste da {0}",
  
	// MARK: Lang command
	'The language has been changed to {0} **{1}**.': 'La lingua è stata cambiata in {0} **{1}**.',
	'Which language would you like to set? \nHere is a list of the available languages:': 'Che lingua vorresti impostare? \nEcco una lista di lingue disponibili:',
	'That is an invalid language. Here are the available languages:': 'Quella non è una lingua valida. Ecco le lingue disponibili:',
  
	// MARK: About command
	'{0} is an all-in-one Discord bot dedicated to helping modding communities and more.': "{0} è un bot tutto-in-uno dedicato all'aiuto delle community di modding e non solo.",
	"It can fulfill your server's moderation needs and create fun events for your community to enjoy": 'Può soddisfare il bisogno di moderazione del tuo server e create eventi divertenti che la tua community può godersi',
	"If you'd like to see all the available commands, please take a look at our website or use the `{0}commands` command": 'Se vuoi vedere una lista dei comandi disponibili, controlla il nostro sito web o usa il comando `{0}commands`',
	'Invite {0} to your server': 'Invita {0} nel tuo server',
	'Requires `MANAGE_SERVER` permissions': 'Richiede che tu abbia il permesso di gestire il server',
	'Check out our website': 'Controlla il nostro sito web',
	'Run some of these commands': 'Esegui alcuni di questi comandi',
	'Join our Support Server': 'Entra nel nostro server di supporto',

	// MARK: Bot utilites category
	"Invite Bot": "Invita",
	"Website": "Sito web",
	"Commands": "Comandi",
	"Support Server": "Server di supporto",

	// MARK: Experiece points category
	"Give a server member a specified amount of points.": "Dona a un altro membro del server dei punti",
	"List all those with the highest amount of points": "Elenca quelli che hanno più punti",
	"Shows a user's experience points.": "Mostra i punti esperienza di un utente",
	"bots do not collect Experience Points! Please try this command on a different user": "i bot non collezionano esperienza! Prova con un utente diverso",
	"Yamamura is not in that server. Therefore, I cannot get that server's points": "Yamamura non è in quel server, per cui non posso ottenerne i punti",
	"you may not see the statistics of a server you are not in. Try again later": "non puoi spiare i punti di un server di cui non fai parte. Prova più tardi",
	"you can't see the points of a user who is/was not in the server. Please try again on a different user.": "non puoi vedere i punti di chi non è/era nel server. Riprova con un utente diverso.",

	"This field contains the user you'd like to give server points too. This can either be a mention, username or user ID": "Questo campo contiene l'utente a cui dare i punti. Può essere una menzione, un username o anche un ID", // To
	"Who would you like to donate points to?": "A chi vuoi donare i tuoi punti?",
	"That's not something we can give points to! Try again.": "Non possiamo donare punti a quell'entità! Riprova.",
	"This argument is the amount of points you'd like to donate to the user.": "Questo argomento indica la quantità di punti da donare all'utente.",
	"How many points would you like to donate?": "Quanti punti vorresti donare?",
	"That's an invalid amount of points! Try again": "Non è un quantitativo di punti valido. Riprova",
	"This argument is for the guild ID you'd like your transactions to go through. Will default itself to the guild ID of the current server if its on a server.": "Questo è l'ID del server nel quale donare i punti. Sarà uguale al server corrente se nessuno è specificato.",
	"This is the action you will perform for the user. It can be either adding, setting or removing": "Questa è l'azione da intraprendere sull'utente. Può essere un'aggiunta, una rimozione o un'impostazione.",
	"Used by bot owners to override bot limits": "È usato dagli sviluppatori del bot per oltrepassare i limiti comuni.",
	"you can't give points to someone who is/was not in the server. Please try again on a different user.": "non puoi donare punti a chi non è/era nel server. Riprova con un utente diverso.",
	"you would not benefit from that.": "non ne trarresti beneficio.",
	"you may not steal points!": "non puoi rubare!",
	"You do not have enough points to donate to the user! Please try again once you collect more points": "あなたはそのユーザーに寄付するのに十分なポイントがありません！さらにポイントを集めてからもう一度お試しください",
	"thank you so much for donating {0} points to {1}. They are now at level {2}": "{0}ポイントを{1}に寄付していただき、ありがとうございます。{1}はレベル{2}になりました",
	"\n Unfortunately, that also means you're now down to {0} points, and are now at level {1}": "\n残念ながら、それはまたあなたが{0}ポイントとレベル{1}になり",

	"Leaderboard for {0}": "Leaderboard per {0}",
	"Handled by Yamamura": "Gestito da Yamamura",
	"Top {0} posters": "Top {0}",
	"**{0}. {1}: {2} points (level {3}) \n": "**{0}. {1}：{2} punti (livello {3}）\n",
	" Leaderboard - Top {0}": "Leaderboard - top {0}",
	"Yamamura Leaderboard": "Leaderboard di Yamamura",
	"{0} ({1} points)": "{0}（{1} punti）",

	"Points system handled by Yamamura": "Punteggio gestito da Yamamura",
	"Points": "Punti",
	"Level": "Livello",
	"There's no higher level that this user can reach. This user is already at their maximum level possible.": "このユーザーが到達できるより高いレベルはありません。このユーザーはすでに可能な最大レベルに達しています。",
	"{0} more points until level up!": "さらに{0}ポイントでレベルアップ！",
	"{0} is currently standing at level {1} with {2} points.": "{0}さんは現在、{2}ポイントでレベル{1}です",
	"Showing stats for {0}": "{0}の統計を表示しています",
	"we do not share any servers with this user. Please try again with a different user.": "このユーザーとサーバーを共有しません。 別のユーザーでもう一度お試しください",
  
	"I couldn't find the requested information.": 'Non ho potuto trovare le informazioni richieste.',
	Author: 'Autore',
	Progress: 'Progresso',
	'commander of this package decided to unpublish it.': "l'autore del pacchetto ha deciso di annullarne la pubblicazione.",
	'Choose a number between 1-{0} (in 1 minute, the command will be canceled)': 'Scegli un numero tra 1 e {0} (in un minuto il comando verrà annullato)',
	"Within the next 30 seconds, you'll need to pick a number between 1-{0}. The command will be automatically canceled canceled in 30 seconds if no selection has been made. Alternatively, type `cancel` to manually cancel the command, skipping the countdown": 'Entro i prossimi 30 secondi, dovrai scegliere un numero compreso tra 1 e {0}. Il comando verrà automaticamente annullato tra 30 secondi se non sarà stato scelto nessun brano. In alternativa, puoi scrivere `cancel` per annullare il comando, saltando il countdown.',
	'{0}ms': '{0}ms',
	'The message round-trip took {0}': "L'invio del messaggio andata e ritorno ha impiegato {0}",
	'The heartbeat ping is {0}': 'Il ping heartbeat è {0}',
	'Welcome to {0}': 'Benvenuto a {0}',
	"If you'd like to see all the available commands, please take a look at our website or type {0}commands": "Per vedere tutti i comandi, dai un'occhiata alla nostra pagina web o digita {0}commands",
	Publicity: 'Pubblicità',
	Usage: 'Utilizzo',
	'Resource Usage': 'Utilizzo Risorse',
	Backends: 'Backend',
	'Database System': 'Database',
	day: 'giorno',
	days: 'giorni',
	hour: 'ora',
	hours: 'ore',
	minute: 'minuto',
	minutes: 'minuti',
	second: 'secondo',
	seconds: 'secondi',
	and: 'e',
	ago: 'fa',
	Uptime: 'Tempo di attività',
	'Creation date': 'Data di creazione',
	'Total Events': 'Eventi',
	'{0} total commands': '{0} comandi',
	'{0} total listeners': '{0} azioni assegnate ad eventi', // Woah, this is really hard to translate ~Samplasion
	"You didn't specify a key!": 'Non hai specificato una chiave!',
	"You didn't specify a value!": 'Non hai specificato un valore!',
	'Are you ___**100%**___ sure you want to reset the configuration? [Y/N]': 'Sei sicuro al ___**100%**___ di voler ripristinare la configurazione? [Y (sì)/N (no)]',
	'action cancelled': 'azione annullata',
	"There's no `{0}` key in the configuration!": "Non c'è alcuna chiave `{0}` nella configurazione!",
	'There has been an error while clearing the configuration. Please report this bug to the {0} Developers': 'Si è verificato un errore durante il ripristino della configurazione. Riporta il bug agli sviluppatori di {0}',
	'{0} - by {1}': '{0} - di {1}',
	'An error occurred: {0}.\nAlert the bot owners to let them fix this error': 'Si è verificato un errore: {0}.\nAvvisa gli sviluppatori per far correggere questo errore',
	"There's no type with ID `{0}`": 'Non esiste alcun tipo con ID `{0}`',
	'The action must be one of [{0}]!': "L'azione deve essere una di [{0}]!",
	'Server configuration for {0}': 'Configurazizone del server {0}',
	'This value is empty': 'Questo valore è vuoto',
	'You can use `{0}config set <key> null` to set a value to an empty state.': 'Usa `{0}config set <chiave> null` per impostare un valore su vuoto.',
	'The input `{0}` is not valid for the type `{1}`.': 'Il valore `{0}` non è valido per il tipo `{1}`',
	Administration: 'Amministrazione',
	'MakerBoard Connectivity': 'Connettività a MakerBoard',
	"View and set your server's config for the bot.": 'Visualizza e modifica la configurazione del server per il bot.',
	'Log channel': 'Canale di log',
	'Welcome channel': 'Canale di benvenuto',
	'Welcome messages': 'Messaggi di benvenuto',
	'Leave message': 'Messaggio di abbandono',
	Prefix: 'Prefisso',
	'MakerBoard URL': 'URL MakerBoard',
	'Starboard channel': 'Canale Starboard',
	'Level UP messages': 'Messaggi di level UP',
	'Level UP': 'Level UP',
	'Muted role': 'Ruolo silenziato',
	'You need to have the configuration key `mutedrole` set in order for this command to work.': 'Perché questo comando possa funzionare, la chiave di configurazione `mutedrole` deve essere impostata.',
	'The user you wanted to mute needs to be in this server in order for this command to work.': "Perché questo comando possa funzionare, l'utente che hai provato a silenziare deve essere nel server.",
	"Administrators can't be muted. It wouldn't affect them.": 'Gli amministratori non possono essere silenziati. Non avrebbe effetto.',
	'You need to have the `Administrator` permission in order to mute moderators.': 'Devi avere il permesso di `Amministratore` per silenziare i moderatori.',
	"You can't mute someone who has a higher role position than you.": 'Non puoi silenziare qualcuno che ha un ruolo con la posizione più alta della tua.',
	"You can't mute yourself!": 'Non ti puoi silenziare da solo!',
	'{0} was successfully muted': '{0} è stato silenziato.',
	'{0} was successfully unmuted': '{0} può di nuovo parlare.',
	'an error occured while trying to mute the user. Report this error to the Yamamura developers: `{0}`': "si è verificato un errore mentre l'utente veniva silenziato. Avverti gli sviluppatori di Yamamura di questo errore: `{0}`",
	Enabled: 'Abilitato',
	Disabled: 'Non abilitato',
  
	'I have successfully paused {0}.': 'Ho messo in pausa {0}.',
	'I think it may work better if you are in a voice channel!': 'Credo funzionerebbe meglio se tu fossi in un canale vocale.',
  
	'I have successfully cleared the configuration': 'Ho ripristinato la configurazione.',
	"I couldn't get text to mock.": "Non c'era testo da prendere in giro.",
	'There were no text I can find to convert to hexadecimal.': "Non c'era testo da convertire in esadecimale.",
	'There was no Bs found in the text': "Non c'erano B nel testo",
	'Related Videos': 'Video consigliati',
	'in order to pause audio, there needs to be audio playing in the channel': 'per mettere in pausa la musica, ci deve essere della musica in riproduzione nel server.',
	'in order to resume audio, there needs to be audio playing in the channel': 'per riprendere la musica, ci deve essere della musica in riproduzione nel server.',
	'Pause the currently playing audio.': 'Metti in  pausa la musica in riproduzione',
	'Shows information on the currently playing song.': 'Mostra informazioni sul brano in riproduzione',
	'Plays the audio of a Youtube video.': 'Riproduce un video di YouTube',
	'Please state a song from Youtube you\'d like to listen to': 'Inserisci un video di YouTube da riprodurre',
	'That\'s not a valid song! Try again.': 'Non è un brano valido! Riprova',
	'Shows the music queue for the current server.': 'Mostra la coda di riproduzione del server.',
	'you need to be in a voice channel in order for me to play music': 'devi essere in un canale vocale prima di far partire la musica',
	'You lost perms to connect to the Voice Channel.': 'Non hai il permesso di connetterti al Canale Vocale',
	"I can't join. Make sure I have the proper permissions.": 'Non posso entrare. Assicurati che io abbia i permessi per farlo',
	"I can't speak. Make sure I have the proper permissions.": 'Non posso parlare. Assicurati che io abbia i permessi per farlo',
	'Related Music Search': 'Ricerca musica correlata',
	'Added {0} song(s) to Queue: {1} | Requested by: {2}': 'Aggiunte {0} canzone/i alla Coda: {1} | Richiesto da: {2}',
	'Aggiunto alla coda: {0} | Richiesto da: {1}': '',
	'{0} Users': '{0} Utenti',
	'{0} Channels': '{0} Canali',
	'{0} Servers': '{0} Servers',
  
	'': '',
	'': '',
	'': '',
	'': '',
	'': '',
	'': '',
  };
  
  language["Within the next 30 seconds, you'll need to pick a number between 1-{0}. "
  + 'The command will be automatically canceled canceled in 30 seconds if no selection has been made.'
  + 'Alternatively, type `cancel` to manually cancel the command, skipping the countdown'] = 'Nei prossimi 30 secondi, dovrai selezionare un numero tra 1 e {0}. Il comando verrà automaticamente annullato in 30 secondi se nessuna selezione verrà effettuata. In alternativa, scrivi `cancel` per annullare il comando, saltando il conto alla rovescia.';
  
  module.exports = language;
  